import { FormEvent, useEffect, useState } from 'react'
import { api, Answer, Health } from './api'
import './styles.css'

export default function App(){
 const [health,setHealth]=useState<Health|null>(null),[indexed,setIndexed]=useState(false),[question,setQuestion]=useState(''),[answer,setAnswer]=useState<Answer|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const [chunkSize,setChunkSize]=useState(1200),[overlap,setOverlap]=useState(200),[topK,setTopK]=useState(5),[dirty,setDirty]=useState(false)
 const refresh=async()=>{try{const [h,d,c]=await Promise.all([api.health(),api.document(),api.config()]);setHealth(h);setIndexed(d.indexed);setChunkSize(Number(c.chunk_size));setOverlap(Number(c.chunk_overlap));setTopK(Number(c.retrieval_top_k));setError('')}catch(e){setError(e instanceof Error?e.message:'Service unavailable')}}
 useEffect(()=>{void refresh()},[])
 const ingest=async(force=false)=>{setBusy(true);setError('');try{await api.ingest(force,chunkSize,overlap);setDirty(false);await refresh()}catch(e){setError(e instanceof Error?e.message:'Ingestion failed')}finally{setBusy(false)}}
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!question.trim())return;setBusy(true);setError('');setAnswer(null);try{setAnswer(await api.query(question,topK))}catch(err){setError(err instanceof Error?err.message:'Query failed')}finally{setBusy(false)}}
 return <main>
  <header><div><p className="eyebrow">LOCAL · PRIVATE · GROUNDED</p><h1>Human Pose Estimation<br/><span>Book Assistant</span></h1></div><div className={`status ${health?.status??'degraded'}`}><i/>{health?.status==='ready'?'All systems ready':'Setup required'}</div></header>
  <section className="service-grid" aria-label="Service status">{[['Ollama',health?.ollama],['Qdrant',health?.qdrant],['Book index',health?.index]].map(([name,state])=><article key={name as string}><b>{name as string}</b><span className={state && (state as Health['ollama']).ok?'ok':'bad'}>{state?(state as Health['ollama']).detail:'Checking…'}</span></article>)}</section>
  <div className="layout"><section className="panel ask"><h2>Ask the book</h2><p>Answers use only retrieved passages and include page citations.</p><form onSubmit={submit}><label htmlFor="question">Your question</label><textarea id="question" value={question} maxLength={2000} onChange={e=>setQuestion(e.target.value)} placeholder="How are 2D human poses represented?" rows={4}/><button disabled={busy||!indexed||!question.trim()}>{busy?'Working…':'Find grounded answer'} <span>→</span></button></form>{error&&<p role="alert" className="error">{error}</p>}
  {answer&&<article className="answer" aria-live="polite"><div className="answer-head"><span>{answer.status==='grounded'?'Grounded answer':'Insufficient context'}</span><small>{Math.round(answer.timing.total_ms)} ms</small></div><p>{answer.answer}</p>{answer.citations.length>0&&<div className="citations"><h3>Sources</h3>{answer.citations.map(c=><details key={c.chunk_id}><summary><b>Page {c.page}</b><span>{c.chapter??'Unlabeled section'}</span><em>{c.score.toFixed(3)}</em></summary><p>{c.excerpt}</p></details>)}</div>}</article>}</section>
  <aside className="panel settings"><h2>Index settings</h2><p>Character-based chunk controls. Changes require re-indexing.</p><label>Chunk size <input type="number" min="200" max="8000" value={chunkSize} onChange={e=>{setChunkSize(+e.target.value);setDirty(true)}}/></label><label>Overlap <input type="number" min="0" max="2000" value={overlap} onChange={e=>{setOverlap(+e.target.value);setDirty(true)}}/></label><label>Retrieved passages <input type="number" min="1" max="25" value={topK} onChange={e=>setTopK(+e.target.value)}/></label>{dirty&&<p className="warning">Chunk settings changed. Re-index before querying.</p>}<button className="secondary" disabled={busy||chunkSize<=overlap} onClick={()=>void ingest(indexed)}>{indexed?'Re-index book':'Index book'}</button><small>The book is mounted read-only. Re-indexing replaces the active index only after a successful build.</small></aside></div>
 </main>
}

